version: '2.21'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: webapp
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://database:27017/mydb
    depends_on:
      - database

  database:
    image: mongo:4.4.6
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  tests:
    image: webapp
    environment:
      - API_URL=http://webapp:3000
    depends_on:
      - webapp
    command: [ "yarn", "test", "test.spec.js" ]

volumes:
  mongodb-data:
    external: true
